### ISSUE TITLE
SkyConnect - Reverting to dual firmware

### ISSUE THREAD

**Issue by henrikeri** [NabuCasa/silabs-firmware#10]
Hi,

Which firmware am I supposed to flash to my SkyConnect if I want to revert to the dual firmware? EmberZNetAndOpenThreadRCP or RCPMultiPAN

**Comment by puddly** [comment]
You would flash the RCP multi-PAN firmware. The addon will do it for you when you check the "Automatically flash firmware" option.

**Comment by agners** [comment]
@henrikeri this is an issue tracker which tracks issues in the firmwares itself. For support, please use our community forum at https://community.home-assistant.io/.
