### ISSUE TITLE
Error: Failed to probe running application type

### ISSUE THREAD

**Issue by Liionboy** [NabuCasa/silabs-firmware#13]
```
adrian@adrian-huawei-d16:~/silabs-firmware$ universal-silabs-flasher --device /dev/serial/by-id/usb-Nabu_Casa_SkyConnect_v1.0_42235ee39a42ed1197c047ab2a61ed69-if00-port0 \
    --baudrate 115200 --bootloader-baudrate 115200 \
    flash --allow-cross-flashing --firmware EmberZNet/beta/NabuCasa_SkyConnect_EZSP_v7.1.4.0_ncp-uart-hw_115200.gbl
2023-02-08 13:17:45 adrian-huawei-d16 universal_silabs_flasher.flash[42821] INFO Extracted GBL metadata: NabuCasaMetadata(metadata_version=1, sdk_version=<AwesomeVersion SemVer '4.1.4'>, ezsp_version=<AwesomeVersion SimpleVer '7.1.4.0'>, fw_type=<FirmwareImageType.NCP_UART_HW: 'ncp-uart-hw'>)
2023-02-08 13:17:45 adrian-huawei-d16 universal_silabs_flasher.flasher[42821] INFO Probing ApplicationType.GECKO_BOOTLOADER
2023-02-08 13:17:47 adrian-huawei-d16 universal_silabs_flasher.flasher[42821] INFO Probing ApplicationType.CPC
2023-02-08 13:17:51 adrian-huawei-d16 universal_silabs_flasher.flasher[42821] INFO Probing ApplicationType.EZSP
Error: Failed to probe running application type
```

**Comment by agners** [comment]
This issue should be posted in the [universal-silabs-flasher repository](https://github.com/NabuCasa/universal-silabs-flasher).

Make sure you've disabled/stopped any service or tool accessing the port  at the same time.

**Comment by Liionboy** [comment]
i find the problem, is because of baaudrate :D

**Comment by Koky05** [comment]
What do you change and how? I have same result as you had.

**Comment by agners** [comment]
It depends what you flashed before, but if you're firmware is using a higher baudrate, you'd adjust the `--baudrate 115200` to be something else, e.g. `--baudrate 230400`

**Comment by Koky05** [comment]
I never flash it before. It is as I bought it, becasue I always get that error.

**Comment by adradr** [comment]
> This issue should be posted in the [universal-silabs-flasher repository](https://github.com/NabuCasa/universal-silabs-flasher).
> 
> Make sure you've disabled/stopped any service or tool accessing the port at the same time.

I had the same issue and found here the solution, so I will put it up here:
1. Install the corresponding driver (I was using MacOS) from here: https://www.silabs.com/developers/usb-to-uart-bridge-vcp-drivers?tab=downloads
2. Re-connect the dongle
3. Use the following command as a template to flash:
```
universal-silabs-flasher --device /dev/tty.SLAB_USBtoUART --baudrate 115200 --bootloader-baudrate 115200 flash --allow-cross-flashing --firmware EmberZNet/NabuCasa_SkyConnect_EZSP_v7.1.1.0_ncp-uart-hw_115200.gbl
```

**Comment by Phillip-VSA** [comment]
Hi.
I'm getting the same error but I am using the Home Assistant Yellow. I have tried changing the baudrate but I've had no luck with it. any idea for what the problem can be?

**Comment by agners** [comment]
Most likely cause is that something else is accessing the device. Maybe a Z2M installation or ZHA is (trying to) accessing the device directly?

**Comment by Phillip-VSA** [comment]
Makes sense, but isn't there a way to se if something is trying to access it in the background so you can turn it off? Because I tried reinstalling home assistant some time back but keep getting the same error
