### ISSUE TITLE
Dependency failure when trying to install

### ISSUE THREAD

**Issue by drrobinson** [NabuCasa/silabs-firmware#15]
Tried to install silabs-firmware on Home Assistant Yellow and got the following errors:

```
Installing collected packages: cffi, aiosignal, cryptography, aiohttp, zigpy, bellows, universal-silabs-flasher
  DEPRECATION: cffi is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for cffi ... error
  error: subprocess-exited-with-error
```
At the bottom was: 
 ```
     error: command 'gcc' failed: No such file or directory
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> cffi
```

**Comment by drrobinson** [comment]
FYI, same problem in **universal-silabs-flasher**

**Comment by agners** [comment]
> Tried to install silabs-firmware on Home Assistant Yellow and got the following errors:

Which environment exactly (Terminal, in one of the containers)?

**Comment by drrobinson** [comment]
SSH into the yellow directly.

**Comment by empaa** [comment]
Can confirm the same behavior on Home Assistant Blue, connecting via SSH and “SSH & Web Terminal” addon. Pip needs gcc to build cffi dependency for the board but gcc is not available in Hass OS.

**Comment by emagnier** [comment]
FYI I had the same problem while using the official "Terminal & SSH" add-on of HA, but it was fixed with the "SSH & Web Terminal" community add-on (with the protected mode set to off on this add-on).

**Comment by agners** [comment]
> SSH into the yellow directly.

There are different environments you can SSH in (host OS, official Terminal & SSH add-on, community SSH & Web Terminal add-on). The Wiki article [Flash Silicon Labs radio firmware manually](https://github.com/NabuCasa/silabs-firmware/wiki/Flash-Silicon-Labs-radio-firmware-manually) recommends the community SSH & Web Terminal, and this seems to work here (running HAOS 9.5).

**Comment by drrobinson** [comment]
I am using SSH & Web Terminal with protected mode disabled.

Don't think it is related since the error is actually about a deprecated installer.

**Comment by krekos** [comment]
i manually installed dependencies than succesfully instaled the flasher

apk add python3 python3-dev gcc libffi-dev libc-dev

**Comment by drrobinson** [comment]
That suggestion actually got me past the dependency error. Thanks for that @krekos 

Now failing when trying to run silabs-flasher

```
➜  ~ curl -O https://github.com/NabuCasa/silabs-firmware/raw/main/EmberZNet/NabuCasa_EZSP_v7.1.1.0_PA32_ncp-uart-hw_115200.gbl
silabs-flasher --device=/dev/ttyAMA1 flash --cm4-gpio-reset --firmware NabuCasa_EZSP_v7.1.1.0_PA32_ncp-uart-hw_115200.gbl 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  203k    0  203k    0     0   303k      0 --:--:-- --:--:-- --:--:--  303k
Trying to connect using EZSP...
Failed communicating using EZSP, assuming we are in bootloader.
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/serial/serialposix.py", line 322, in open
    self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/ttyAMA1'
```

**Comment by agners** [comment]
You also have to disable the protection mode to get hardware access.

**Comment by agners** [comment]
@bert269 it is an option in the add-on. Make sure to install the "SSH & Web Terminal" (from the Community Add-ons section).

**Comment by agners** [comment]
Assume fixed.
