### ISSUE TITLE
Old/wrong URL to universal-silabs-flasher in guide in wiki for silabs-firmware 

### ISSUE THREAD

**Issue by Hedda** [NabuCasa/silabs-firmware#16]
https://github.com/NabuCasa/silabs-firmware/wiki/Flash-Silicon-Labs-radio-firmware-manually

under Preparation section has wrong/old URL universal-silabs-flasher pointing to https://github.com/puddly/universal-silabs-flasher/ instead of pointing to https://github.com/NabuCasa/universal-silabs-flasher

```
Install the [universal-silabs-flasher](https://github.com/puddly/universal-silabs-flasher/) available on the PyPI:

$ pip install universal-silabs-flasher
Download the firmware files, e.g. by downloading this repository:

git clone https://github.com/NabuCasa/silabs-firmware.git

```

**Comment by agners** [comment]
Fixed, thanks for bringing this up!
