### ISSUE TITLE
Different EmberZNet parameters in README and silabs-firmware-builder

### ISSUE THREAD

**Issue by ksjh** [NabuCasa/silabs-firmware#18]
The parameters in the ``build.yaml`` for the EmberZNet builds in [silabs-firmware-builder repo](https://github.com/NabuCasa/silabs-firmware-builder/blob/main/.github/workflows/build.yaml) are different from those in the table in the ``README.md`` of this project. Are the firmware files here really built with the parameters in the *Zigbee PRO stack macro* table of the README?

**Comment by agners** [comment]
Thanks for noticing, I've updated the README.md.
