### ISSUE TITLE
Increase UART speed for multi-protocol firmware.

### ISSUE THREAD

**Issue by ekobres** [NabuCasa/silabs-firmware#19]
The default 115.2kbps rate for multi-protocol is very slow given all of the additional traffic it must handle. 
The IEEE 802.15.4 data rate is up to 250kbps, meaning that in a busy network, many incoming frames to the RCP could be dropped, resulting in re-transmits, compounding the problem.

Add to this the double-duty of handling both Zigbee and Thread traffic, and normal operations like startup and discovery will essentially always overrun the RCP interface.

I currently have a Thread network with 62 devices, and it takes HK Controller upwards of 10 minutes to connect to all of them using a foreign OTBR. (Pi3 + nRF52840 dongle.)

During this time, I see repeated instances of messages like the following:

```
Mar 20 11:07:41 Pi3b31 otbr-agent[572]: 20:06:35.655 [I] Mle-----------: Receive Advertisement (fe80:0:0:0:d47e:28a2:9c6d:278f,0x1800)
Mar 20 11:07:41 Pi3b31 otbr-agent[572]: 20:06:35.737 [N] MeshForwarder-: Dropping rx frag frame, error:Drop, len:88, src:0xd40e, dst:0x8404, tag:29549, offset:104, dglen:1184, sec:yes
Mar 20 11:07:41 Pi3b31 otbr-agent[572]: 20:06:35.746 [N] MeshForwarder-: Dropping rx frag frame, error:Drop, len:88, src:0xd40e, dst:0x8404, tag:29549, offset:192, dglen:1184, sec:yes
Mar 20 11:07:41 Pi3b31 otbr-agent[572]: 20:06:35.757 [N] MeshForwarder-: Dropping rx frag frame, error:Drop, len:88, src:0xd40e, dst:0x8404, tag:29549, offset:280, dglen:1184, sec:yes
Mar 20 11:07:41 Pi3b31 otbr-agent[572]: 20:06:35.765 [N] MeshForwarder-: Dropping rx frag frame, error:Drop, len:88, src:0xd40e, dst:0x8404, tag:29549, offset:368, dglen:1184, sec:yes
Mar 20 11:07:41 Pi3b31 otbr-agent[572]: 20:06:35.775 [N] MeshForwarder-: Dropping rx frag frame, error:Drop, len:88, src:0xd40e, dst:0x8404, tag:29549, offset:456, dglen:1184, sec:yes
Mar 20 11:07:41 Pi3b31 otbr-agent[572]: 20:06:35.786 [I] MeshForwarder-: Received IPv6 UDP msg, len:107, chksum:5a05, ecn:no, from:0x1c00, sec:yes, prio:normal, rss:-52.0
Mar 20 11:07:41 Pi3b31 otbr-agent[572]: 20:06:35.786 [I] MeshForwarder-:     src:[fdb4:413:b0ea:1:8e25:8944:5237:93d9]:5683
Mar 20 11:07:41 Pi3b31 otbr-agent[572]: 20:06:35.786 [I] MeshForwarder-:     dst:[fdf2:21be:6c1c:4d62:9244:472c:5c5:93ba]:52573
Mar 20 11:07:41 Pi3b31 otbr-agent[572]: 20:06:35.792 [I] MeshForwarder-: Received IPv6 HopOpts msg, len:86, chksum:0000, ecn:no, from:0x8400, sec:yes, prio:normal, rss:-52.0
Mar 20 11:07:41 Pi3b31 otbr-agent[572]: 20:06:35.792 [I] MeshForwarder-:     src:[fd7d:e897:7f23:a698:0:ff:fe00:8404]
Mar 20 11:07:41 Pi3b31 otbr-agent[572]: 20:06:35.792 [I] MeshForwarder-:     dst:[ff03:0:0:0:0:0:0:2]
Mar 20 11:07:41 Pi3b31 otbr-agent[572]: 20:06:35.807 [I] MeshForwarder-: Received IPv6 HopOpts msg, len:86, chksum:0000, ecn:no, from:0x8400, sec:yes, prio:normal, rss:-52.0
Mar 20 11:07:41 Pi3b31 otbr-agent[572]: 20:06:35.807 [I] MeshForwarder-:     src:[fd7d:e897:7f23:a698:0:ff:fe00:8404]
Mar 20 11:07:41 Pi3b31 otbr-agent[572]: 20:06:35.807 [I] MeshForwarder-:     dst:[ff03:0:0:0:0:0:0:2]
Mar 20 11:07:41 Pi3b31 otbr-agent[572]: 20:06:35.824 [I] MeshForwarder-: Sent IPv6 UDP msg, len:134, chksum:d261, ecn:no, to:0x8400, sec:yes, prio:low
Mar 20 11:07:41 Pi3b31 otbr-agent[572]: 20:06:35.824 [I] MeshForwarder-:     src:[fdf2:21be:6c1c:4d62:9244:472c:5c5:93ba]:52573
Mar 20 11:07:41 Pi3b31 otbr-agent[572]: 20:06:35.824 [I] MeshForwarder-:     dst:[fdb4:413:b0ea:1:8e25:8944:5237:93d9]:5683
Mar 20 11:07:41 Pi3b31 otbr-agent[572]: 20:06:35.827 [I] Mac-----------: Frame rx failed, error:UnknownNeighbor, len:70, seqnum:124, type:Data, src:0x0800, dst:0xffff, sec:yes, ackreq:no
Mar 20 11:07:41 Pi3b31 otbr-agent[572]: 20:06:35.829 [I] Mac-----------: Frame rx failed, error:UnknownNeighbor, len:70, seqnum:40, type:Data, src:0x8c00, dst:0xffff, sec:yes, ackreq:no
Mar 20 11:07:41 Pi3b31 otbr-agent[572]: 20:06:35.834 [I] Mac-----------: Frame rx failed, error:UnknownNeighbor, len:70, seqnum:84, type:Data, src:0x3000, dst:0xffff, sec:yes, ackreq:no
Mar 20 11:07:41 Pi3b31 otbr-agent[572]: 20:06:35.840 [N] MeshForwarder-: Dropping rx frag frame, error:Drop, len:88, src:0xd40e, dst:0x8404, tag:29549, offset:896, dglen:1184, sec:yes
Mar 20 11:07:41 Pi3b31 otbr-agent[572]: 20:06:35.846 [I] Mac-----------: Frame rx failed, error:UnknownNeighbor, len:70, seqnum:2, type:Data, src:0x9400, dst:0xffff, sec:yes, ackreq:no
Mar 20 11:07:41 Pi3b31 otbr-agent[572]: 20:06:35.854 [N] MeshForwarder-: Dropping rx frag frame, error:Drop, len:88, src:0xd40e, dst:0x8404, tag:29549, offset:984, dglen:1184, sec:yes
Mar 20 11:07:41 Pi3b31 otbr-agent[572]: 20:06:35.859 [I] Mac-----------: Frame rx failed, error:UnknownNeighbor, len:70, seqnum:234, type:Data, src:0xd800, dst:0xffff, sec:yes, ackreq:no
```

It is not even possible to keep the Si Labs Add-on OTBR with SkyConnect running while this is occurring. It crashes repeatedly under the strain. (related Skyconnect boot-loop issue here: https://github.com/home-assistant/addons/issues/2922)

I believe that increasing the UART speed could eliminate the bottleneck at the RCP and at least mitigate the issue.

I built the rcp firmware for my nRF52840 dongle from source, but I have so far avoided trying to build the multi-protocol firmware for SkyConnect because I don't have any info on the make flags used to build it.

Would it be possible to add that information to this project, build the firmware from source here, and maybe even provide an experimental version with higher speed UART settings?

(Apologies if the info is out there and I missed it somewhere obvious!)

**Comment by ekobres** [comment]
There is an interesting comment thread on a related performance issue opened on the ot-efr32 GitHub.
Note their results with worse performance and higher packet loss with slower UART speed settings:

https://github.com/openthread/ot-efr32/issues/280#issuecomment-1090231986

**Comment by MattWestb** [comment]
Little interesting but i dont getting if they was getting it working in the end or not and it was one problem with TCP in the OTRB that was disabled for getting it working (its one year old so many bugs shall being fixed now).
I is running most of my OTBR on " IKEA Billy" (EFR32MG1P) and some hardware (SOC UART) cant handle more then 105200 and other higher with USB-TTL but i have no optimal cable from the Zigbee module and the USB-TTL chip that can making it cant using higher speed.
If going to high the addon is complaining of CRC errors in the CPC communication then communicating with the RCP and its not flow control related then the the buffer is not filled  on both sides.

My feeling is 921600 bardrate is not needed but 105200 is to low then the WPAN is running in 256K but is overhead in both protocols so at least 230400 is needed and if the hardware is OK is 460800 the optimal but it shall being interesting if the SC is running stable at 921600 for all devices then i shall recommending using it as standard for all SC thread firmware.

**Comment by agners** [comment]
Thanks for all your input, just to be clear, I am well aware that we should bump the baudrate. We actually started with 230400 at one point. However, we reverted to 115200 for simplicity. Increasing the baudrate is an effort which is work-in-progress.

The main challenge was automatically flashing the firmware with SkyConnect: SkyConnect does not have a hardware method to enter boot loader, so we need to talk to the firmware currently running. For that, the universal-silabs-flasher needs to try talking multiple "languages" to detect the firmware currently running. In a first step, this was challenging enough, so we limited our self's to a single baud rate at first.

Just yesterday @puddly worked on multi-baudrate support, see https://github.com/NabuCasa/universal-silabs-flasher/pull/23.

Once that is in, we can start deploying firmwares with different baud rates. Currently we are thinking to go with 460800 directly.

**Comment by agners** [comment]
Since we have adventurous folks around here :smile: :  You can find firmware builds for Home Assistant SkyConenct (and Yellow) using 460800 at https://github.com/NabuCasa/silabs-firmware-builder/actions/runs/4498685224. Keep in mind that once flashed with this firmare, re-flashing lower baud rates currently needs manually executing the universal-silabs-flasher.

**Comment by ekobres** [comment]
>  You can find firmware builds for Home Assistant SkyConnect (and Yellow) using 460800 at https://github.com/NabuCasa/silabs-firmware-builder/actions/runs/4498685224. 

Over on Discord I learned RCP-only FW was already 460.8K - is this build any different for RCP - or does this just make it consistent across FW types?

I already flashed from Multi-pan to RCP-only successfully - testing that now. 

As a suggestion - would it make sense to implement some sort of safe-mode functionality like with ExpressHome or other projects? Basically just power off and on the Skyconnect some number of times in a row and enter safe boot mode?

**Comment by agners** [comment]
> Over on Discord I learned RCP-only FW was already 460.8K - is this build any different for RCP - or does this just make it consistent across FW types?

Yes, OT RCP was at 460800 only. This bump was only for Multi-PAN firmware (as this issue is about).



> As a suggestion - would it make sense to implement some sort of safe-mode functionality like with ExpressHome or other projects? Basically just power off and on the Skyconnect some number of times in a row and enter safe boot mode?

Interesting idea. Not sure if this is easily doable (probably depends quite a bit on HW, non-volatile memory available etc.)

**Comment by MattWestb** [comment]
Normal Zigbee light is having it implanted with 6 fast repower of the device for doing factory reset that  can being re programmed but i dont if its one function in the standalone / app bootloader or is being made in the main app or one combination of both.

**Comment by agners** [comment]
Firmwares with higher baudrates are available now: https://github.com/NabuCasa/silabs-firmware/commit/9f47abe79e775095883904285405b6d132380f06.

Integration into add-on is work-in-progress right now: https://github.com/home-assistant/addons/pull/2950.
