### ISSUE TITLE
Error When Flashing

### ISSUE THREAD

**Issue by launchm** [NabuCasa/silabs-firmware#20]
I have been unable to flash the device and now it will not work at all.

<img width="903" alt="Screenshot 2023-03-21 at 14 51 59" src="https://user-images.githubusercontent.com/2204760/226644953-25dfa6cd-e03c-4b83-b9a8-0aa20170551a.png">

**Comment by agners** [comment]
Which version of `univeral-silabs-flasher` are you using?

This probably belongs to the issue tracker of https://github.com/NabuCasa/universal-silabs-flasher.
