### ISSUE TITLE
Add abbreviations legend to readme?

### ISSUE THREAD

**Issue by Hedda** [NabuCasa/silabs-firmware#22]
Suggest adding an abbreviations legend to readme file to help users interpret the file names of all the different firmware images.

Believe these were previously commonly used shorthand and acronyms used in firmware image file names for Silabs based adapters:

* ncp = Silabs NCP
* s2 = EFR32 Series 2 (eg. EFR32MG2x such as EFR32MG21)
* s1 = EFR32 Series 1 (eg. EFR32MG1x)
* F1024 = 1024k Flash Size
* F512 = 512k Flash Size
* F256 = 256k Flash Size
* com = Combined (necessary for EFR32 Series 1)
* uart = UART interface
* nsw = no flow control
* sw = software flow control (XON/XOFF flow control)
* hw = hardware flow control (RTS/CTS flow control - Only supported by ZB-GW04 V1.2)
* 655 / 678 / 679 = EmberZNet Version which also indoicate version for EZSP (EmberZNet Serial Protocol)
* 115200 = Baud rate speed set to 115200
* 57600 = Baud rate speed set to 57600
* std = Standalone
* btl = Bootloader
* PB00-PB01 = Port used for TXD (Transceive Data) and RXD (Receive Data)
* PA00 = Bootloader GPIO Activation

Other abbreviations have also been known to be used within the community that releases official and unofficial Silabs firmware images. 

See references:
https://github.com/xsp1989/zigbeeFirmware/blob/master/firmware/Zigbee3.0_Dongle-NoSigned/EZSP/README.md
https://github.com/grobasoz/zigbee-firmware/blob/master/EFR32%20Series%202/EFR32MG21A020F1024/README.md
https://github.com/MattWestb/EFR32-FW/blob/main/Soff_EZSP/README.md
https://github.com/zha-ng/EZSP-Firmware/blob/master/Elelabs-ELU013/README.md
https://github.com/walthowd/husbzb-firmware
https://github.com/Elelabs/elelabs-zigbee-ezsp-utility/tree/master/data/EFR32MG13
https://github.com/Elelabs/elelabs-zigbee-ezsp-utility/tree/master/data/EFR32MG21
https://github.com/skgsergio/silabs-multiprotocol-firmware-zbgw04-usb/tree/main/firmware

**Comment by agners** [comment]
As we archive this repository this won't become any attention here. Closing.
