### ISSUE TITLE
SkyConnect - OpenThread "No response to 'Command.read_parameter' command with seq id '0x02'"

### ISSUE THREAD

**Issue by fooman** [NabuCasa/silabs-firmware#24]
I am trying to use SkyConnect as a thread only device. I have flashed this firmware

[NabuCasa_SkyConnect_OpenThread_RCP_v2.3.0.0_ot-rcp_hw_460800.gbl](https://github.com/NabuCasa/silabs-firmware/blob/main/OpenThreadRCP/NabuCasa_SkyConnect_OpenThread_RCP_v2.3.0.0_ot-rcp_hw_460800.gbl)

Home Assistant (2023.7.1) is running in a docker instance and I have exposed the usb device to the container. I believe this to have worked as Home Assistant sees the device and offering to configure it:
![image](https://github.com/NabuCasa/silabs-firmware/assets/455508/a97412f4-b34c-4a09-b221-33a3e6bd9ab8)
as well as this in the logs:
```
homeassistant-home-assistant2:/config# dmesg | grep ttyUSB0
[   80.469842] usb 1-1: cp210x converter now attached to ttyUSB0
[856109.165331] cp210x ttyUSB0: cp210x converter now disconnected from ttyUSB0
[856541.841160] usb 1-1: cp210x converter now attached to ttyUSB0
```

Unfortunately trying to set it up 
![image](https://github.com/NabuCasa/silabs-firmware/assets/455508/0e55a1da-9892-4a6b-8a7b-765cc13239f6)

yields "Failed to probe the usb device"
![image](https://github.com/NabuCasa/silabs-firmware/assets/455508/14a0bc88-cff4-4b2c-a3b5-4c2bab0aa64e)

and this in the logs:
```
2023-07-07 14:58:27.666 WARNING (MainThread) [zigpy_deconz.api] No response to 'Command.read_parameter' command with seq id '0x02'
```

A similar result happens when I manually try to set up ZHA
![image](https://github.com/NabuCasa/silabs-firmware/assets/455508/aab9e262-b520-49d3-8922-d3ff7faf5cc9)

using
![image](https://github.com/NabuCasa/silabs-firmware/assets/455508/07b22493-4db9-4d88-af6b-c7570a078d0e)

and 
![image](https://github.com/NabuCasa/silabs-firmware/assets/455508/160e808a-35d0-4a0e-abf5-a6dd920fef41)

which comes up as "Failed to Connect"
![image](https://github.com/NabuCasa/silabs-firmware/assets/455508/cf474d95-47bc-47e1-9e50-483e392c8b4f)

but nothing in the home-assistant.log files.

At this point I am not sure if this is an issue with the device itself, the firmware, home assistant or my set up. Any help in narrowing this down is appreciated.

**Comment by agners** [comment]
> I am trying to use SkyConnect as a thread only device. I have flashed this firmware

Well, if you did that, then you can't use it with ZHA anymore.  ZHA is Zigbee only, that is a different protocol. The OpenThread RCP firmware is fundamentally incompatible with ZHA.

If you want a Thread border router instead, you have to use the "OpenThread Border Router" add-on. Once the add-on is installed, select the SkyConnect in the Add-on config, and start the add-on. The OpenThread Border Router should then automatically appear as an integration as well, and a new network should show up in the Thread integration configuration panel.

**Comment by fooman** [comment]
Thanks @agners that makes sense - HA did autodetect the ZHA integration.

Unfortunately it's not coming up in the config and directly asks for the url
![image](https://github.com/NabuCasa/silabs-firmware/assets/455508/45e8fb5f-8b4c-4807-91fe-cdc0f5300456)

I think I'll just cut my losses for now and wait this out for another few months to see if this becomes possible.

**Comment by agners** [comment]
When you enabled the ZHA config option, ZHA might have disturbed the startup phase of the add-on, in which case the add-on logs should show an error.

To be sure, I suggest the following:
1. Remove the ZHA integration
2. Make sure you have the "OpenThread Border Router" add-on installed and "Start on boot" active
3. Make sure you _don't_ have any other add-on installed which accesses the same device (e.g. make sure that "Silicon Labs Multiprotocol" or "Zigbee2MQTT" is uninstalled!)
4. Restart the HA instance (technically, restarting the add-on should be enough, but a complete restart should really make sure that you start from a clean slate)
5. After restart, under Devices & Services, an integration "Open Thread Border Router" should appear.

I've  just checked discovery on my end on Home Assistant OS 10.3 with the OpenThread Border Router 2.2.0 add-on.

**Comment by fooman** [comment]
@agners thanks for the extra suggestions. This is using the Home Assistant docker image so not OS and I am guessing that attaching skyconnect to the container directly is not enough for the docker image to handle it. I will experiment further with using a standalone docker image for just the openthread router in the future.
