### ISSUE TITLE
[REQUEST] Silcon Labs Zigbee EmberZNet 7.1.4.0 & 7.2.3.0 firmware image

### ISSUE THREAD

**Issue by lysiong** [NabuCasa/silabs-firmware#29]
as the EmberZNet 7.1.4.0 & 7.2.3.0 is listed on the readme but didn't list up in archive folder, may I know where can I find that 2 firmware? I use it for testing the new zigbee switch as it is not able to join the z2m, it keep on left the network.

**Comment by Milfeldt** [comment]
@lysiong look in beta

**Comment by lysiong** [comment]
@Milfeldt I didn't notice the file is at beta folder, thanks for the reply :)
