### ISSUE TITLE
[Question] Firmware useable on SONOFF Zigbee 3.0 USB Dongle Plus-E?

### ISSUE THREAD

**Issue by Calimerorulez** [NabuCasa/silabs-firmware#4]
Hi,

I was searching for more recent firmware for my SONOFF Zigbee 3.0 USB Dongle Plus-E (what a mouthful ;) ), and I came across this repo.

Could this firmware for Amber and Yellow also be useable on other EFR32MG21 based dongles like the new SONOFF one?

**Comment by agners** [comment]
We use the MGM210P module, and I assume SONOFF uses a SoC directly. I *think* SiLabs checks somehow if its running on the module/SoC it is compiled for, so this might be an issue.

Another problem is, the UART pinout. I think we followed the SDK and use PA05 for TX, and PA06 for RX, PC01 for RTS and PD02 for CTS. If SONOFF uses the same pinout, it *might* even work.

**Comment by agners** [comment]
FWIW, it's definitely not supported/intended :sweat_smile:

**Comment by Calimerorulez** [comment]
Hi @agners 
FWIW, I tried flashing the 7.1 firmwares, but the stick is dead in the water after that; booting in bootloader mode (press and hold the boot button and then plug in the USB connection) revives the bootloader and lets me flash the Sonoff formware.

Thanks for your reply :)

**Comment by agners** [comment]
Ok, thanks for reporting.
