### ISSUE TITLE
silabs-flasher is missing declaring gpiod as a required module

### ISSUE THREAD

**Issue by rolf-tx** [NabuCasa/silabs-firmware#7]
I believe 'silabs-flasher' is missing declaring required gpiod as a required module.

Error when running silabs-flasher:
`  File "/usr/local/bin/silabs-flasher", line 198, in flash import gpiod                                                          
ModuleNotFoundError: No module named 'gpiod'     `

Works after 'pip install gpiod'

**Comment by agners** [comment]
It is only required when using the `--cm4-gpio-reset` flag, therefor I made it an extra dependency, see:
https://github.com/agners/silabs-flasher#silicon-labs-firmware-flashing-utility

**Comment by rolf-tx** [comment]
@agners Thanks, your silab-flasher documentation is clear.

It would be good if silab-firmware readme got updated to add gpiod to the pip install instructions
